CREATE TABLE `addon_options` (
   `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
   `addon_type_id` BIGINT UNSIGNED NOT NULL,
   `label` VARCHAR(50) NOT NULL,
   `price_cents` BIGINT UNSIGNED NOT NULL DEFAULT 0,
   `is_default` TINYINT(1) NOT NULL DEFAULT 0,
   `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
   `updated_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
   FOREIGN KEY (addon_type_id) REFERENCES addon_types(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;